"""State models and execution traces for the Multi-Step Agentic workflow."""
from typing import Any, Literal
from pydantic import BaseModel, Field

from src.rag.simple_rag import SourceCitation, VerificationResult


class SubQuestionExecution(BaseModel):
    """Detailed record of a decomposed sub-question execution."""
    step_num: int
    sub_question: str
    active_query: str
    rewrites: list[str] = Field(default_factory=list)
    attempts: int = 1
    chunks: list[SourceCitation] = Field(default_factory=list)
    is_sufficient: bool = True
    assessment_notes: str = ""


class AgentPlan(BaseModel):
    """Initial strategic decomposition plan generated by the LLM."""
    query: str
    strategy: str
    involved_domains: list[str] = Field(default_factory=list)
    sub_questions: list[str] = Field(default_factory=list)


class AgentTrace(BaseModel):
    """Comprehensive chronological trace of all agentic execution steps."""
    plan: AgentPlan
    sub_executions: list[SubQuestionExecution] = Field(default_factory=list)
    total_rewrites: int = 0
    total_unique_chunks: int = 0
    draft_answer: str = ""
    claims_verification: VerificationResult | None = None


class AgentResponse(BaseModel):
    """Complete response emitted by the Multi-Step Agentic Orchestrator."""
    query: str
    workflow: str = "agentic"
    answer: str
    confidence: float = 1.0
    sources: list[SourceCitation] = Field(default_factory=list)
    trace: AgentTrace
    abstained: bool = False
    model_used: str = ""
    latency_seconds: float = 0.0

    def to_dict(self) -> dict[str, Any]:
        return {
            "query": self.query,
            "workflow": self.workflow,
            "answer": self.answer,
            "confidence": self.confidence,
            "sources": [s.model_dump() for s in self.sources],
            "trace": {
                "plan": self.trace.plan.model_dump(),
                "sub_executions": [e.model_dump() for e in self.trace.sub_executions],
                "total_rewrites": self.trace.total_rewrites,
                "total_unique_chunks": self.trace.total_unique_chunks,
                "draft_answer": self.trace.draft_answer,
                "claims_verification": self.trace.claims_verification.model_dump() if self.trace.claims_verification else None,
            },
            "abstained": self.abstained,
            "model_used": self.model_used,
            "latency_seconds": round(self.latency_seconds, 3),
        }
